#!/bin/bash

# Ensure we are just below the home directory
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
if [[ "$(readlink -f $here/..)" != "$(readlink -f $HOME)" ]]; then
    echo "Bootstrap expects itself to be one level below \$HOME" 1>&2
    exit 1
fi
cd $here

# Warn on incompatible shell version
if [[ ${BASH_VERSION%%.*} -lt 4 ]]; then
    echo "Warning: requires bash 4+, this is ${BASH_VERSION}" 1>&2
fi

# Warn on missing commands
for cmd in stow m4 xrdb xprop xsetroot xset python3; do
    if ! command -v $cmd &>/dev/null; then
        echo "Warning: command unavailable: $cmd" 1>&2
    fi
done

# i3
mkdir -p ~/.i3/bin &>/dev/null
${STOW:-stow} i3

# bash
${STOW:-stow} bash

# bin
mkdir -p ~/bin &>/dev/null
${STOW:-stow} bin

# vim
mkdir -p ~/.vim/colors &>/dev/null
${STOW:-stow} vim

# gdb 
mkdir -p ~/.cgdb &>/dev/null
${STOW:-stow} gdb

