divert(-1)
define(M4_COLOR_HILIGHT_FG,`0')
define(M4_COLOR_HILIGHT_BG,`7')
define(M4_COLOR_COMMENT_FG,`10')
define(M4_COLOR_CONSTANT_FG,`6')
define(M4_COLOR_STATEMENT_FG,`2')
define(M4_COLOR_PREPROC_FG,`9')
define(M4_COLOR_TYPE_FG,`3')
divert(0)dnl
