set backspace=2

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

:au FileType cpp setlocal tabstop=2 shiftwidth=2 softtabstop=2 cindent
:au FileType tcl setlocal tabstop=2 shiftwidth=2 softtabstop=2
:au FileType make setlocal noexpandtab

set cursorline
set hlsearch
set showmatch
set matchtime=0
syntax enable

set number
set relativenumber
nmap <F3> <Esc>:set nu! rnu!<CR>

nnoremap Q <nop>

" *last-position-jump*
:au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

set backup
set swapfile
set undofile
if !isdirectory($HOME."/.vim/backups")
    silent! execute "!mkdir ~/.vim/backups"
endif
set backupdir=~/.vim/backups//
if !isdirectory($HOME."/.vim/swaps")
    silent! execute "!mkdir ~/.vim/swaps"
endif
set directory=~/.vim/swaps//
if !isdirectory($HOME."/.vim/undos")
    silent! execute "!mkdir ~/.vim/undos"
endif
set undodir=~/.vim/undos//

" Disable swap/etc on large files (>10M)
let g:LargeFileSz = 10 * 1024 * 1024
augroup LargeFile
    au!
    autocmd BufReadPre * let sz=getfsize(expand("<afile>")) | if sz > g:LargeFileSz || sz == -2 | call LargeFileMode() | endif
augroup END
function! LargeFileMode()
    " Disable swap file, undo; unload hidden buffers for memory savings
    setlocal noswapfile
    setlocal undolevels=-1
    setlocal bufhidden=unload
    autocmd VimEnter * echo "Large file mode activated"
endfunction

" Source theme last
try
    source ~/.vim/theme
catch
endtry

