divert(-1)
define(M4_COLOR_HILIGHT_FG,`7')
define(M4_COLOR_HILIGHT_BG,`0')
define(M4_COLOR_COMMENT_FG,`8')
define(M4_COLOR_CONSTANT_FG,`5')
define(M4_COLOR_STATEMENT_FG,`4')
define(M4_COLOR_PREPROC_FG,`4')
define(M4_COLOR_TYPE_FG,`4')
divert(0)dnl
